#Configure the sensor addition
CONFIG_SENSOR=y
CONFIG_MPU6050=y

#I2C
CONFIG_I2C=y

#Logging
CONFIG_LOG=y

#Shell

CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

#Print
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Float math
CONFIG_FPU=y

#NVS
CONFIG_NVS=y
CONFIG_FLASH=y
#needed for fixed partition
CONFIG_FLASH_MAP=y
CONFIG_CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_FP_SUPPORT=y